// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartStock.Api.Infrastructure.Persistence;

#nullable disable

namespace smartStock.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410184953_RemoverIdentity_UsuarioPropio")]
    partial class RemoverIdentity_UsuarioPropio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("smartStock.Api.Domain.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SesionCompraId")
                        .HasColumnType("int");

                    b.Property<int?>("SesionVentaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCompras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SesionCompraId")
                        .IsUnique()
                        .HasFilter("[SesionCompraId] IS NOT NULL");

                    b.HasIndex("SesionVentaId")
                        .IsUnique()
                        .HasFilter("[SesionVentaId] IS NOT NULL");

                    b.ToTable("CierreCaja");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemTransaccionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("ItemTransaccionCompra");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemTransaccionVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GananciaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("ItemTransaccionVenta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemCompraId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemVentaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemCompraId")
                        .IsUnique()
                        .HasFilter("[ItemCompraId] IS NOT NULL");

                    b.HasIndex("ItemVentaId")
                        .IsUnique()
                        .HasFilter("[ItemVentaId] IS NOT NULL");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientoStock");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioAltaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioAltaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.SesionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSesion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionCompra");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.SesionVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSesion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionVenta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.StockActual", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductoId");

                    b.ToTable("StockActual");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TransaccionCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("SesionCompraId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SesionCompraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TransaccionCompra");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TransaccionVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("SesionVentaId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SesionVentaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TransaccionVenta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId", "Rol");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CierreCaja", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.SesionCompra", "SesionCompra")
                        .WithOne("CierreCaja")
                        .HasForeignKey("smartStock.Api.Domain.Models.CierreCaja", "SesionCompraId");

                    b.HasOne("smartStock.Api.Domain.Models.SesionVenta", "SesionVenta")
                        .WithOne("CierreCaja")
                        .HasForeignKey("smartStock.Api.Domain.Models.CierreCaja", "SesionVentaId");

                    b.Navigation("SesionCompra");

                    b.Navigation("SesionVenta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemTransaccionCompra", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.TransaccionCompra", "Transaccion")
                        .WithMany("Items")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemTransaccionVenta", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.TransaccionVenta", "Transaccion")
                        .WithMany("Items")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.MovimientoStock", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.ItemTransaccionCompra", "ItemCompra")
                        .WithOne("Movimiento")
                        .HasForeignKey("smartStock.Api.Domain.Models.MovimientoStock", "ItemCompraId");

                    b.HasOne("smartStock.Api.Domain.Models.ItemTransaccionVenta", "ItemVenta")
                        .WithOne("Movimiento")
                        .HasForeignKey("smartStock.Api.Domain.Models.MovimientoStock", "ItemVentaId");

                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCompra");

                    b.Navigation("ItemVenta");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Producto", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "UsuarioAlta")
                        .WithMany("Productos")
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UsuarioAlta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.SesionCompra", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Proveedor", "Proveedor")
                        .WithMany("SesionesCompra")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("SesionesCompra")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.SesionVenta", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("SesionesVenta")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.StockActual", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithOne("Stock")
                        .HasForeignKey("smartStock.Api.Domain.Models.StockActual", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TransaccionCompra", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.SesionCompra", "SesionCompra")
                        .WithMany("Transacciones")
                        .HasForeignKey("SesionCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionCompra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TransaccionVenta", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.SesionVenta", "SesionVenta")
                        .WithMany("Transacciones")
                        .HasForeignKey("SesionVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionVenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Usuario", b =>
                {
                    b.OwnsOne("smartStock.Api.Domain.Models.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.UsuarioRol", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemTransaccionCompra", b =>
                {
                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemTransaccionVenta", b =>
                {
                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Producto", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Proveedor", b =>
                {
                    b.Navigation("SesionesCompra");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.SesionCompra", b =>
                {
                    b.Navigation("CierreCaja");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.SesionVenta", b =>
                {
                    b.Navigation("CierreCaja");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TransaccionCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TransaccionVenta", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Productos");

                    b.Navigation("Roles");

                    b.Navigation("SesionesCompra");

                    b.Navigation("SesionesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
