// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartStock.Api.Infrastructure.Persistence;

#nullable disable

namespace smartStock.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("smartStock.Api.Domain.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UsuarioAltaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UsuarioAltaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompraDiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalCompras")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("VentaDiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompraDiaId")
                        .IsUnique()
                        .HasFilter("[CompraDiaId] IS NOT NULL");

                    b.HasIndex("VentaDiaId")
                        .IsUnique()
                        .HasFilter("[VentaDiaId] IS NOT NULL");

                    b.ToTable("CierresCaja");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CodigoProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_CodigosProducto_Codigo");

                    b.HasIndex("ProductoId");

                    b.ToTable("CodigosProducto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CompraDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSesion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComprasDia");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompraDiaId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaAnulada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaComprobante")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("UsuarioAnulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompraDiaId");

                    b.HasIndex("UsuarioAnulaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProveedorId", "NumeroComprobante", "TipoComprobante")
                        .IsUnique()
                        .HasDatabaseName("UX_DetallesCompra_Comprobante")
                        .HasFilter("[NumeroComprobante] IS NOT NULL AND [EstaAnulada] = 0");

                    b.ToTable("DetallesCompra");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaAnulada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MontoRecibido")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroComprobante")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("UsuarioAnulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VentaDiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAnulaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaDiaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemDetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("CodigoProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DetalleCompraId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Factor")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProductoId");

                    b.HasIndex("DetalleCompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsDetalleCompra");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemDetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("CodigoProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DetalleVentaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Factor")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("GananciaTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProductoId");

                    b.HasIndex("DetalleVentaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsDetalleVenta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemCompraId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemVentaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemCompraId");

                    b.HasIndex("ItemVentaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioAltaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioAltaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cuit")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioAltaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasFilter("[Cuit] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.HasIndex("UsuarioAltaId");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.StockActual", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductoId");

                    b.ToTable("StocksActuales");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.TokenRevocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("TokensRevocados", (string)null);
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId", "Rol");

                    b.HasIndex("Rol")
                        .IsUnique()
                        .HasDatabaseName("UX_UsuarioRoles_Administrador")
                        .HasFilter("[Rol] = 'Administrador'");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.VentaDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSesion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FechaSesion")
                        .IsUnique()
                        .HasDatabaseName("UX_VentasDia_FechaSesion");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VentasDia");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Categoria", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioAlta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CierreCaja", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.CompraDia", "CompraDia")
                        .WithOne("CierreCaja")
                        .HasForeignKey("smartStock.Api.Domain.Models.CierreCaja", "CompraDiaId");

                    b.HasOne("smartStock.Api.Domain.Models.VentaDia", "VentaDia")
                        .WithOne("CierreCaja")
                        .HasForeignKey("smartStock.Api.Domain.Models.CierreCaja", "VentaDiaId");

                    b.Navigation("CompraDia");

                    b.Navigation("VentaDia");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CodigoProducto", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany("Codigos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CompraDia", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("ComprasDia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.DetalleCompra", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.CompraDia", "CompraDia")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Proveedor", "Proveedor")
                        .WithMany("Detalles")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "UsuarioAnula")
                        .WithMany()
                        .HasForeignKey("UsuarioAnulaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompraDia");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnula");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.DetalleVenta", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "UsuarioAnula")
                        .WithMany()
                        .HasForeignKey("UsuarioAnulaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.VentaDia", "VentaDia")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnula");

                    b.Navigation("VentaDia");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemDetalleCompra", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.CodigoProducto", "CodigoProducto")
                        .WithMany()
                        .HasForeignKey("CodigoProductoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("smartStock.Api.Domain.Models.DetalleCompra", "DetalleCompra")
                        .WithMany("Items")
                        .HasForeignKey("DetalleCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoProducto");

                    b.Navigation("DetalleCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemDetalleVenta", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.CodigoProducto", "CodigoProducto")
                        .WithMany()
                        .HasForeignKey("CodigoProductoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("smartStock.Api.Domain.Models.DetalleVenta", "DetalleVenta")
                        .WithMany("Items")
                        .HasForeignKey("DetalleVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoProducto");

                    b.Navigation("DetalleVenta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.MovimientoStock", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.ItemDetalleCompra", "ItemCompra")
                        .WithMany("Movimientos")
                        .HasForeignKey("ItemCompraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("smartStock.Api.Domain.Models.ItemDetalleVenta", "ItemVenta")
                        .WithMany("Movimientos")
                        .HasForeignKey("ItemVentaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ItemCompra");

                    b.Navigation("ItemVenta");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Producto", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "UsuarioAlta")
                        .WithMany("Productos")
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UsuarioAlta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Proveedor", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "UsuarioAlta")
                        .WithMany()
                        .HasForeignKey("UsuarioAltaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("smartStock.Api.Domain.Models.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("ProveedorId");

                            b1.ToTable("Proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();

                    b.Navigation("UsuarioAlta");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.StockActual", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Producto", "Producto")
                        .WithOne("Stock")
                        .HasForeignKey("smartStock.Api.Domain.Models.StockActual", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Usuario", b =>
                {
                    b.OwnsOne("smartStock.Api.Domain.Models.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.UsuarioRol", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.VentaDia", b =>
                {
                    b.HasOne("smartStock.Api.Domain.Models.Usuario", "Usuario")
                        .WithMany("VentasDia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.CompraDia", b =>
                {
                    b.Navigation("CierreCaja");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.DetalleCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.DetalleVenta", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemDetalleCompra", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.ItemDetalleVenta", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Producto", b =>
                {
                    b.Navigation("Codigos");

                    b.Navigation("Movimientos");

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Proveedor", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.Usuario", b =>
                {
                    b.Navigation("ComprasDia");

                    b.Navigation("Movimientos");

                    b.Navigation("Productos");

                    b.Navigation("Roles");

                    b.Navigation("VentasDia");
                });

            modelBuilder.Entity("smartStock.Api.Domain.Models.VentaDia", b =>
                {
                    b.Navigation("CierreCaja");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
